### ISSUE TITLE
Add emojis support for buttons.

### ISSUE THREAD

**Issue by CosmicCodeBase** [merlinfuchs/embed-generator#96] opened 2023-09-26 07:58 UTC
Please add custom and normal emoji support for buttons.

**Comment by Pohy101** [comment] 2023-09-26 08:41
It's already been suggested.
https://github.com/users/merlinfuchs/projects/1/views/1?filterQuery=emoji+buttons

**Comment by merlinfuchs** [comment] 2023-09-26 18:45
closing this because it's a duplicate of #23

**Closed by merlinfuchs** 2023-09-26 18:45 UTC
