### ISSUE TITLE
Docker container immediately crashes and restarts.

### ISSUE THREAD

**Issue by Leolele99** [merlinfuchs/embed-generator#90] opened 2023-06-26 19:08 UTC
After playing around with selfhosting a bit, I have run into a problem:

I can selfhost the service on baremetal just fine on multiple machines, but as soon as I try to use the docke image, it crashes with no error (looks similar to having a misconfigured api.host on bare metal, but since both just dont have any error messages its hard to diagnose or say if its the same error).

I am using the same config.yaml file for both dockerized and bare metal and have connection to the docker postgres db from the docker container of embed-generator (verified using ./embedg-server migrate postgres up), I am a bit lost for what to do.

Since you probably use the docker image yourself to host your live version, I would love to get some additional information about a docker/docker compose setup and if there are any special cases I have to look out for (I already modified the startup command to "./embedg-server server").

Greetings, 

Leo

**Comment by merlinfuchs** [comment] 2023-06-26 19:15
Hi Leo, the docker image was never nested by myself. I just copied the workflow over from one my other projects and just assumed it would work. 
If you know what the issue is and think you can fix it I would be really happy to accept a PR!

**Comment by Leolele99** [comment] 2023-06-26 19:33
I'll take a look, but I am entirely new to go and the other languages being used in this project.

Is there any way to enable a more verbose logging? The flags -d and -D didn't change anything.

Furthermore, I saw that some components look for errors and log them, but since I am not getting anything it would have to be before any of this happens. And since the only other time I was able to trigger a crash with no logging was by writing garbage as the api.host field, is there anything that is especially sensitive in that bit of code, especially if some networking might be affected?

Finally, is there any kind of archtiecture/network map, this way it makes it a bit easier to see what should happen during a normal startup and go through it bit by bit, since I can't really debug the compiled code.

Thanks for your quick reply, 
LG Leo

**Comment by merlinfuchs** [comment] 2023-06-26 19:43
A silent crash is usually caused by an fatal error which can some times not be logged to the console. I would guess it's a misconfiguration of api.host or api.port but there are quite a few places where we log a fatal error: https://github.com/search?q=repo%3Amerlinfuchs%2Fembed-generator%20.Fatal&type=code
It might also be that it can't connect to the postgres database from the docker container 🤔 

Sadly the logging library some times fails to actually flush the message to the console before exiting the process. That's why you don't see any error message.

**Comment by merlinfuchs** [comment] 2023-10-19 10:51
This should be fixed, take a look at the updated README with instructions for docker-compose.

**Closed by merlinfuchs** 2023-10-19 10:51 UTC
Labels: bug
